import type { Metadata } from "next";
import Script from "next/script";
import { Plus_Jakarta_Sans, Fraunces, Noto_Sans_Arabic } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getTranslations } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Analytics } from "@vercel/analytics/next";
import { JsonLd } from "@/components/schema/json-ld";
import "./globals.css";

const GTM_ID = "GTM-MPT7HMNM";
const GA_ID = "G-W1D7NNYKQE";

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://tadnun.com";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-playfair",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const notoArabic = Noto_Sans_Arabic({
  variable: "--font-arabic",
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

type Locale = (typeof routing.locales)[number];

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "meta" });
  const pageUrl = `${BASE_URL}/${locale}`;

  return {
    metadataBase: new URL(BASE_URL),
    title: {
      default: t("title"),
      template: `%s — Tadnun`,
    },
    description: t("description"),
    keywords: [
      "digital transformation Morocco",
      "digitalisation Maroc",
      "التحول الرقمي المغرب",
      "Moroccan business software",
      "logiciel entreprise Maroc",
      "Tadnun",
      "تدنون",
      "Morocco business digitalization",
      "digitalisation entreprise Maroc",
    ],
    authors: [{ name: "Tadnun", url: BASE_URL }],
    creator: "Tadnun",
    publisher: "Tadnun",
    formatDetection: {
      email: false,
      telephone: false,
    },

    // Open Graph (image auto-generated by opengraph-image.tsx)
    openGraph: {
      type: "website",
      siteName: "Tadnun",
      title: t("title"),
      description: t("description"),
      url: pageUrl,
      locale: locale === "ar" ? "ar_MA" : locale === "fr" ? "fr_MA" : "en",
    },

    // Twitter Card (image auto-generated by twitter-image.tsx)
    twitter: {
      card: "summary_large_image",
      title: t("title"),
      description: t("description"),
    },

    // Hreflang alternates for all locales
    alternates: {
      canonical: pageUrl,
      languages: {
        fr: `${BASE_URL}/fr`,
        en: `${BASE_URL}/en`,
        ar: `${BASE_URL}/ar`,
        "x-default": `${BASE_URL}/fr`,
      },
    },

    // Favicon
    icons: {
      icon: [
        { url: "/favicon.svg", type: "image/svg+xml" },
      ],
      apple: "/apple-touch-icon.png",
    },

    // Verification (add when you have search console)
    // verification: {
    //   google: "your-google-verification-code",
    // },
  };
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  const messages = (await import(`../../messages/${locale}.json`)).default;

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={`${jakarta.variable} ${fraunces.variable} ${notoArabic.variable} antialiased`}
    >
      <head>
        {/* Google Tag Manager */}
        <Script
          id="gtm-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','${GTM_ID}');`,
          }}
        />
        {/* Google Analytics (gtag.js) */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
          strategy="afterInteractive"
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '${GA_ID}');`,
          }}
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <noscript>
          <iframe
            src={`https://www.googletagmanager.com/ns.html?id=${GTM_ID}`}
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        <JsonLd locale={locale} />
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
